title: Juncture
tagline: Your Visual Essays tool
banner: /images/hero-juncture.png
favicon: /images/favicon.svg

# When using a custom domain these fields must be updated to match
# the account and repository name
#acct: <GitHub account/username>
#repo: <GitHub repository>

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: About
  icon: info
  path: /about
- label: Help
  icon: question
  path: /docs
- label: Contact Us
  icon: envelope
  path: "/contact-us"

# If the /contact-us path is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form
# A valid toEmail address is required. Other fields are optional
contactForm:
  toEmail:
  #- labs@ithakaorg.onmicrosoft.com
  - Ron.Snyder@ithaka.org
  subject: Juncture Contact Form

#######################################################
# Base URL of server used for IIIF presentation manifests
######################################################
iiifServer: https://iiif.juncture-digital.org

siteAdmins:
- rsnyder

fontawesome: https://kit.fontawesome.com/19541ddce8.js

ghUnscopedToken: Z2hwX05lcnV2RUYzRmx6M3o5YnFjQWZuOGpJQnJMR3lEMTNmYjYyVw==
gcAuthDomain: anVuY3R1cmUtZGlnaXRhbC5maXJlYmFzZWFwcC5jb20=
gcApiKey: QUl6YVN5Qk9ia1dHU3NDMXhmX1o3ckZRNC1oRkJ1NVpvTjdxaDBv

gaPropertyID: UA-125778965-6
