title: Juncture
tagline: A Visual Essay Site
banner: https://picsum.photos/1000/400
favicon: /images/favicon.svg
customCSS: /css/custom.css

# When using a custom domain these fields must be updated to match
# the account and repository name
#acct: <GitHub account/username>
#repo: <GitHub repository>

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: About
  icon: info
  path: /about
#- label: Contact Us
#  icon: envelope
#  path: "/contact-us"

# If the /contact-us path is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form.
contactForm:
  toEmail:
  - Ron Snyder <ronald.snyder@ithaka.org>
  subject: Contact Us

#######################################################
# Base URL of server used for serving and optionally
# creating IIIF presentation manifests
######################################################
iiifServer: https://iiif.juncture-digital.org

siteAdmins:
- rsnyder

######################################################
# Optional credentials used for GitHub API and OAuth integration
######################################################

# GitHub upscoped API token used for content retrivals
#ghUnscopedToken: <Base64 encoded GitHub unscoped token>

# Google Cloud OAuth settings for GithHub login via Juncture
#gcAuthDomain: <Base64-encoded Google Cloud OAuth domain>
#gcApiKey: <Base64-encoded restricted access Google Cloud API key>
